CREATE TABLE IF NOT EXISTS characters (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  state JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS directives (
  id SERIAL PRIMARY KEY,
  channel_id TEXT NOT NULL,
  directive TEXT NOT NULL
);
